### ISSUE TITLE
how to limit max voltage?

### ISSUE THREAD

**Issue by peepo** [adafruit/Adafruit-40-pin-TFT-Friend#2]
there is a broad range of tft displays that use 40pin fpc, and have same pinout.

However many of these have 20.4v maximum voltage.

is there a simple way to adapt this unit, and change Vout?

thanks

**Comment by ladyada** [comment]
its current limited, the voltage adjusts automatically.

**Comment by peepo** [comment]
easily asserted, the fact is the backlight on my display [WF35YTIACDNN0-WSR](https://www.texim-europe.com/getfile.ashx?id=107485)
only briefly flashes on, before cutting out.
the current requirement is similar to adafruit screens
